apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: TestString
          jsonPath: .testString # foo.ymlの階層(spec配下なら.spec.testString)
          type: string
        - name: TestNum
          jsonPath: .testNum
          type: integer
      schema: # 新しいフィールドを追加
        openAPIV3Schema:
          type: object
          properties:
            testString:
              type: string
            testNum:
              type: integer